### ISSUE TITLE
extract_single runtime error when trying to extract audio files

### ISSUE THREAD

**Issue by Evan8456** [sensein/b2aiprep#104] opened 2024-12-18 21:11 UTC
Code used: 
```
from b2aiprep.prepare.prepare import extract_single
from glob import glob
import pydra
from pathlib import Path

fl = [Path(v).absolute() for v in sorted(glob("peds_audio/**/*.wav", recursive=True))]

extract_task = pydra.mark.task(extract_single)(
        transcription_model_size='large-v3-turbo',
        with_sensitive=True,
        cache_dir=Path('cache').absolute(),
    )
extract_task.split("wav_path", wav_path=fl)
with pydra.Submitter(plugin='cf', n_procs=2) as run:
    run(extract_task)

if __name__ == '__main__':
    pass
```
Error:
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/evanng/mambaforge/lib/python3.10/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/home/evanng/mambaforge/lib/python3.10/multiprocessing/spawn.py", line 125, in _main
    prepare(preparation_data)
  File "/home/evanng/mambaforge/lib/python3.10/multiprocessing/spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "/home/evanng/mambaforge/lib/python3.10/multiprocessing/spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "/home/evanng/mambaforge/lib/python3.10/runpy.py", line 289, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/home/evanng/mambaforge/lib/python3.10/runpy.py", line 96, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/home/evanng/mambaforge/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/evanng/Documents/b2aiprep_bids_audio_output/audio.py", line 15, in <module>
    run(extract_task)
  File "/home/evanng/mambaforge/lib/python3.10/site-packages/pydra/engine/submitter.py", line 55, in __call__
    self.loop.run_until_complete(
  File "/home/evanng/mambaforge/lib/python3.10/site-packages/nest_asyncio.py", line 99, in run_until_complete
    return f.result()
  File "/home/evanng/mambaforge/lib/python3.10/asyncio/futures.py", line 201, in result
    raise self._exception.with_traceback(self._exception_tb)
  File "/home/evanng/mambaforge/lib/python3.10/asyncio/tasks.py", line 234, in __step
    result = coro.throw(exc)
  File "/home/evanng/mambaforge/lib/python3.10/site-packages/pydra/engine/submitter.py", line 96, in submit_from_call
    await self.expand_runnable(runnable, wait=True, rerun=rerun)  # TODO
  File "/home/evanng/mambaforge/lib/python3.10/site-packages/pydra/engine/submitter.py", line 144, in expand_runnable
    await asyncio.gather(*futures)
  File "/home/evanng/mambaforge/lib/python3.10/asyncio/tasks.py", line 304, in __wakeup
    future.result()
  File "/home/evanng/mambaforge/lib/python3.10/asyncio/tasks.py", line 232, in __step
    result = coro.send(None)
  File "/home/evanng/mambaforge/lib/python3.10/site-packages/pydra/engine/workers.py", line 186, in exec_as_coro
    res = await self.loop.run_in_executor(
  File "/home/evanng/mambaforge/lib/python3.10/asyncio/base_events.py", line 821, in run_in_executor
    executor.submit(func, *args), loop=self)
  File "/home/evanng/mambaforge/lib/python3.10/concurrent/futures/process.py", line 732, in submit
    self._adjust_process_count()
  File "/home/evanng/mambaforge/lib/python3.10/concurrent/futures/process.py", line 692, in _adjust_process_count
    self._spawn_process()
  File "/home/evanng/mambaforge/lib/python3.10/concurrent/futures/process.py", line 709, in _spawn_process
    p.start()
  File "/home/evanng/mambaforge/lib/python3.10/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/home/evanng/mambaforge/lib/python3.10/multiprocessing/context.py", line 288, in _Popen
    return Popen(process_obj)
  File "/home/evanng/mambaforge/lib/python3.10/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/home/evanng/mambaforge/lib/python3.10/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/home/evanng/mambaforge/lib/python3.10/multiprocessing/popen_spawn_posix.py", line 42, in _launch
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "/home/evanng/mambaforge/lib/python3.10/multiprocessing/spawn.py", line 154, in get_preparation_data
    _check_not_importing_main()
  File "/home/evanng/mambaforge/lib/python3.10/multiprocessing/spawn.py", line 134, in _check_not_importing_main
    raise RuntimeError('''
RuntimeError: 
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/evanng/mambaforge/lib/python3.10/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/home/evanng/mambaforge/lib/python3.10/multiprocessing/spawn.py", line 125, in _main
    prepare(preparation_data)
  File "/home/evanng/mambaforge/lib/python3.10/multiprocessing/spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "/home/evanng/mambaforge/lib/python3.10/multiprocessing/spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "/home/evanng/mambaforge/lib/python3.10/runpy.py", line 289, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/home/evanng/mambaforge/lib/python3.10/runpy.py", line 96, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/home/evanng/mambaforge/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/evanng/Documents/b2aiprep_bids_audio_output/audio.py", line 15, in <module>
    run(extract_task)
  File "/home/evanng/mambaforge/lib/python3.10/site-packages/pydra/engine/submitter.py", line 55, in __call__
    self.loop.run_until_complete(
  File "/home/evanng/mambaforge/lib/python3.10/site-packages/nest_asyncio.py", line 99, in run_until_complete
    return f.result()
  File "/home/evanng/mambaforge/lib/python3.10/asyncio/futures.py", line 201, in result
    raise self._exception.with_traceback(self._exception_tb)
  File "/home/evanng/mambaforge/lib/python3.10/asyncio/tasks.py", line 234, in __step
    result = coro.throw(exc)
  File "/home/evanng/mambaforge/lib/python3.10/site-packages/pydra/engine/submitter.py", line 96, in submit_from_call
    await self.expand_runnable(runnable, wait=True, rerun=rerun)  # TODO
  File "/home/evanng/mambaforge/lib/python3.10/site-packages/pydra/engine/submitter.py", line 144, in expand_runnable
    await asyncio.gather(*futures)
  File "/home/evanng/mambaforge/lib/python3.10/asyncio/tasks.py", line 304, in __wakeup
    future.result()
  File "/home/evanng/mambaforge/lib/python3.10/asyncio/tasks.py", line 232, in __step
    result = coro.send(None)
  File "/home/evanng/mambaforge/lib/python3.10/site-packages/pydra/engine/workers.py", line 186, in exec_as_coro
    res = await self.loop.run_in_executor(
  File "/home/evanng/mambaforge/lib/python3.10/asyncio/base_events.py", line 821, in run_in_executor
    executor.submit(func, *args), loop=self)
  File "/home/evanng/mambaforge/lib/python3.10/concurrent/futures/process.py", line 732, in submit
    self._adjust_process_count()
  File "/home/evanng/mambaforge/lib/python3.10/concurrent/futures/process.py", line 692, in _adjust_process_count
    self._spawn_process()
  File "/home/evanng/mambaforge/lib/python3.10/concurrent/futures/process.py", line 709, in _spawn_process
    p.start()
  File "/home/evanng/mambaforge/lib/python3.10/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/home/evanng/mambaforge/lib/python3.10/multiprocessing/context.py", line 288, in _Popen
    return Popen(process_obj)
  File "/home/evanng/mambaforge/lib/python3.10/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/home/evanng/mambaforge/lib/python3.10/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/home/evanng/mambaforge/lib/python3.10/multiprocessing/popen_spawn_posix.py", line 42, in _launch
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "/home/evanng/mambaforge/lib/python3.10/multiprocessing/spawn.py", line 154, in get_preparation_data
    _check_not_importing_main()
  File "/home/evanng/mambaforge/lib/python3.10/multiprocessing/spawn.py", line 134, in _check_not_importing_main
    raise RuntimeError('''
RuntimeError: 
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
Traceback (most recent call last):
  File "/home/evanng/Documents/b2aiprep_bids_audio_output/audio.py", line 15, in <module>
    run(extract_task)
  File "/home/evanng/mambaforge/lib/python3.10/site-packages/pydra/engine/submitter.py", line 55, in __call__
    self.loop.run_until_complete(
  File "/home/evanng/mambaforge/lib/python3.10/site-packages/nest_asyncio.py", line 99, in run_until_complete
    return f.result()
  File "/home/evanng/mambaforge/lib/python3.10/asyncio/futures.py", line 201, in result
    raise self._exception.with_traceback(self._exception_tb)
  File "/home/evanng/mambaforge/lib/python3.10/asyncio/tasks.py", line 234, in __step
    result = coro.throw(exc)
  File "/home/evanng/mambaforge/lib/python3.10/site-packages/pydra/engine/submitter.py", line 96, in submit_from_call
    await self.expand_runnable(runnable, wait=True, rerun=rerun)  # TODO
  File "/home/evanng/mambaforge/lib/python3.10/site-packages/pydra/engine/submitter.py", line 144, in expand_runnable
    await asyncio.gather(*futures)
  File "/home/evanng/mambaforge/lib/python3.10/asyncio/tasks.py", line 304, in __wakeup
    future.result()
  File "/home/evanng/mambaforge/lib/python3.10/asyncio/tasks.py", line 234, in __step
    result = coro.throw(exc)
  File "/home/evanng/mambaforge/lib/python3.10/site-packages/pydra/engine/workers.py", line 186, in exec_as_coro
    res = await self.loop.run_in_executor(
  File "/home/evanng/mambaforge/lib/python3.10/asyncio/futures.py", line 285, in __await__
    yield self  # This tells Task to wait for completion.
  File "/home/evanng/mambaforge/lib/python3.10/asyncio/tasks.py", line 304, in __wakeup
    future.result()
  File "/home/evanng/mambaforge/lib/python3.10/asyncio/futures.py", line 201, in result
    raise self._exception.with_traceback(self._exception_tb)
concurrent.futures.process.BrokenProcessPool: A process in the process pool was terminated abruptly while the future was running or pending.
```

**Comment by satra** [comment] 2024-12-18 23:17
do you have a linux machine?

can you add these lines, before creating `extract_task`

```python
import multiprocessing as mp

try:
    mp.set_start_method("spawn", force=True)
except RuntimeError:
    # Already set
    pass
```

also since you are using cache, just remove that directory before rerunning.

**Comment by satra** [comment] 2024-12-19 17:14
that's likely a memory issue. how much memory do you have on the system? two options: reduce `n_procs` to 1 or/and change model to `tiny`.

**Comment by Evan8456** [comment] 2024-12-19 17:24
i have 15.3 gb of memory. The issue seems to still persist even when I run it with `n_procs=1` and with `tiny-v3-turbo`

**Comment by satra** [comment] 2024-12-19 20:26
i'm assuming you created a new environment for this. if not please do create one so that the latest pydra and senselab are downloaded.

regarding the tasks that ran, did it create the pt files in an audio folder?

are you removing the lock files or removing the cache directory when you rerun. 

do you know if there are some really long recordings?

if you want you can simply run the python function without using pydra or a cache directory directly. this will run in series, and will likely crash if something runs out of memory. 

also if you run b2aiprep in developer mode, you could suppress the torchaudio call (or modify parameters) and also pause the speech to text call.

**Comment by Evan8456** [comment] 2024-12-19 22:08
I installed the latest version of pydra and senselab that is compatible with b2aiprep.
The lock files and cache are removed every time I reran.
I just cloned b2aiprep and tried to run it in developer mode, while suppressing the torch audio call. 

I'm able to generate the pt files up until it reaches recordings that are long(1.5 min or longer). I believe this is the cause of my error.

**Comment by satra** [comment] 2024-12-19 22:12
thanks @Evan8456 - could you please file an issue in senselab that we need to work on memory efficiency for long recordings. i'm closing this as we know what the issue is.

**Closed by satra** 2024-12-19 22:12 UTC
